source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               plugin.properties,\
               icons/,\
               *.picto,\
               *.egl,\
               *.egx,\
               *.xmi