#

pluginName = RAAML Picto Studio Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_SafetyAnalysis_type = Safety Analysis
_UI_NamedElement_type = Named Element
_UI_Analysis_type = Analysis
_UI_AbstractLibrary_type = Abstract Library
_UI_CoreSafetyElement_type = Safety Element
_UI_Situation_type = Situation
_UI_FailureMode_type = Failure Mode
_UI_Hazard_type = Hazard
_UI_Error_type = Error
_UI_Fault_type = Fault
_UI_ControllingMeasure_type = Controlling Measure
_UI_Detection_type = Detection
_UI_Recommendation_type = Recommendation
_UI_Mitigation_type = Mitigation
_UI_Prevention_type = Prevention
_UI_State_type = State
_UI_FailureState_type = Failure State
_UI_DirectedRelationship_type = Directed Relationship
_UI_RelevantTo_type = Relevant To
_UI_PresentIn_type = Present In
_UI_Violates_type = Violates
_UI_Item_type = Item
_UI_SingleElementItem_type = Single Element Item
_UI_ElementGroup_type = Element Group
_UI_ElementGroupBasedItem_type = Element Group Based Item
_UI_AnySituation_type = Any Situation
_UI_Factor_type = Factor
_UI_ProcessModelFlaw_type = Process Model Flaw
_UI_HarmPotential_type = Harm Potential
_UI_AbstractEvent_type = Abstract Event
_UI_DysfunctionalEvent_type = Dysfunctional Event
_UI_AbstractEffect_type = Abstract Effect
_UI_UndesiredState_type = Undesired State
_UI_AbstractFailureMode_type = Abstract Failure Mode
_UI_AbstractCause_type = Abstract Cause
_UI_Scenario_type = Scenario
_UI_AbstractRisk_type = Abstract Risk
_UI_Requirement_type = Requirement
_UI_RequirementComponent_type = Requirement Component
_UI_Abstraction_type = Abstraction
_UI_DeriveRequirement_type = Derive Requirement
_UI_IndependenceRequirement_type = Independence Requirement
_UI_ASILDecompose_type = ASIL Decompose
_UI_Satisfy_type = Satisfy
_UI_UserInfoRequirement_type = User Info Requirement
_UI_RecoveryRequirement_type = Recovery Requirement
_UI_DependabilityRequirement_type = Dependability Requirement
_UI_FunctionalSafetyRequirement_type = Functional Safety Requirement
_UI_SoftwareSafetyRequirement_type = Software Safety Requirement
_UI_HardwareSafetyRequirement_type = Hardware Safety Requirement
_UI_TechnicalSafetyRequirement_type = Technical Safety Requirement
_UI_SafetyGoal_type = Safety Goal
_UI_Dependency_type = Dependency
_UI_SafeState_type = Safe State
_UI_OperatingMode_type = Operating Mode
_UI_HazardAndRiskAssessment_type = Hazard And Risk Assessment
_UI_ISO26262SafetyRequirementTemplate_type = ISO26262 Safety Requirement Template
_UI_RequirementsModel_type = Requirements Model
_UI_GeneralLibrary_type = General Library
_UI_FTA_type = FTA
_UI_FTAElement_type = FTA Element
_UI_Event_type = Event
_UI_BasicEvent_type = Basic Event
_UI_IntermediateEvent_type = Intermediate Event
_UI_TopEvent_type = Top Event
_UI_ConditionalEvent_type = Conditional Event
_UI_DormantEvent_type = Dormant Event
_UI_UndevelopedEvent_type = Undeveloped Event
_UI_HouseEvent_type = House Event
_UI_ZeroEvent_type = Zero Event
_UI_Gate_type = Gate
_UI_AND_type = AND
_UI_OR_type = OR
_UI_NOT_type = NOT
_UI_XOR_type = XOR
_UI_SEQ_type = SEQ
_UI_INHIBIT_type = INHIBIT
_UI_MAJORITY_VOTE_type = MAJORITY VOTE
_UI_FTATree_type = FTA Tree
_UI_FTALibrary_type = FTA Library
_UI_FMEA_type = FMEA
_UI_RPNCalculation_type = RPN Calculation
_UI_AbstractFMEAItem_type = Abstract FMEA Item
_UI_FMEAItem_type = FMEA Item
_UI_LossOfFunction_type = Loss Of Function
_UI_DegradationOfFunction_type = Degradation Of Function
_UI_IntermittentFunction_type = Intermittent Function
_UI_PartialFunction_type = Partial Function
_UI_ExceedingFunction_type = Exceeding Function
_UI_UnintendedFunction_type = Unintended Function
_UI_DelayedFunction_type = Delayed Function
_UI_FMEALibrary_type = FMEA Library
_UI_ISO26262_type = ISO26262
_UI_OperationalSituation_type = Operational Situation
_UI_MalfunctioningBehaviour_type = Malfunctioning Behaviour
_UI_Verified_type = Verified
_UI_Confirmed_type = Confirmed
_UI_ASILAssignment_type = ASIL Assignment
_UI_OperationalCondition_type = Operational Condition
_UI_AbstractOperationalSituation_type = Abstract Operational Situation
_UI_AccidentScenario_type = Accident Scenario
_UI_AnyMalfunction_type = Any Malfunction
_UI_HazardousEvent_type = Hazardous Event
_UI_AutomotiveEffect_type = Automotive Effect
_UI_SystemLevelEffect_type = System Level Effect
_UI_VehicleLevelEffect_type = Vehicle Level Effect
_UI_ISO26262Library_type = ISO26262 Library
_UI_STPA_type = STPA
_UI_Loss_type = Loss
_UI_ControlStructure_type = Control Structure
_UI_Controller_type = Controller
_UI_ControlledProcess_type = Controlled Process
_UI_Actuator_type = Actuator
_UI_Sensor_type = Sensor
_UI_ControlAction_type = Control Action
_UI_Feedback_type = Feedback
_UI_UndesiredControlAction_type = Undesired Control Action
_UI_STPALibrary_type = STPA Library
_UI_GSN_type = GSN
_UI_GSNNode_type = GSN Node
_UI_GSNArgumentNode_type = GSN Argument Node
_UI_Goal_type = Goal
_UI_Strategy_type = Strategy
_UI_Solution_type = Solution
_UI_ContextualInformation_type = Contextual Information
_UI_Context_type = Context
_UI_Justification_type = Justification
_UI_Assumption_type = Assumption
_UI_Dependency_type = Dependency
_UI_InContextOf_type = In Context Of
_UI_SupportedBy_type = Supported By
_UI_Rationale_type = Rationale
_UI_ASILOverrideRationale_type = ASIL Override Rationale
_UI_LessonLearned_type = Lesson Learned
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_SafetyAnalysis_analyses_feature = Analyses
_UI_SafetyAnalysis_libraries_feature = Libraries
_UI_SafetyAnalysis_requirements_feature = Requirements
_UI_NamedElement_id_feature = Id
_UI_NamedElement_name_feature = Name
_UI_NamedElement_description_feature = Description
_UI_NamedElement_visibility_feature = Visibility
_UI_Analysis_elements_feature = Elements
_UI_AbstractLibrary_elements_feature = Elements
_UI_ControllingMeasure_affects_feature = Affects
_UI_DirectedRelationship_source_feature = Source
_UI_DirectedRelationship_target_feature = Target
_UI_Item_members_feature = Members
_UI_Item_boundaryMembers_feature = Boundary Members
_UI_SingleElementItem_referencedElement_feature = Referenced Element
_UI_ElementGroup_groupCriterion_feature = Group Criterion
_UI_ElementGroup_orderedMembers_feature = Ordered Members
_UI_AnySituation_from_feature = From
_UI_AnySituation_to_feature = To
_UI_Factor_processModelFlaw_feature = Process Model Flaw
_UI_ProcessModelFlaw_causalFactor_feature = Causal Factor
_UI_ProcessModelFlaw_undesiredControlAction_feature = Undesired Control Action
_UI_HarmPotential_undesiredControlAction_feature = Undesired Control Action
_UI_AbstractEvent_likelihood_feature = Likelihood
_UI_DysfunctionalEvent_toError_feature = To Error
_UI_DysfunctionalEvent_fromError_feature = From Error
_UI_DysfunctionalEvent_error_feature = Error
_UI_DysfunctionalEvent_failure_feature = Failure
_UI_DysfunctionalEvent_fault_feature = Fault
_UI_AbstractEffect_severity_feature = Severity
_UI_AbstractFailureMode_detectability_feature = Detectability
_UI_AbstractCause_occurrence_feature = Occurrence
_UI_AbstractCause_error_feature = Error
_UI_Scenario_scenarioSteps_feature = Scenario Steps
_UI_Scenario_triggers_feature = Triggers
_UI_AbstractRisk_riskScore_feature = Risk Score
_UI_AbstractRisk_harmPotentials_feature = Harm Potentials
_UI_AbstractRisk_harms_feature = Harms
_UI_Requirement_text_feature = Text
_UI_Requirement_type_feature = Type
_UI_Requirement_priority_feature = Priority
_UI_Requirement_status_feature = Status
_UI_Requirement_relatedElements_feature = Related Elements
_UI_Requirement_parentRequirement_feature = Parent Requirement
_UI_Requirement_childRequirements_feature = Child Requirements
_UI_RequirementComponent_haraOwner_feature = Hara Owner
_UI_DeriveRequirement_source_feature = Source
_UI_DeriveRequirement_target_feature = Target
_UI_Satisfy_source_feature = Source
_UI_Satisfy_target_feature = Target
_UI_Dependency_source_feature = Source
_UI_Dependency_target_feature = Target
_UI_HazardAndRiskAssessment_haraRequirements_feature = Hara Requirements
_UI_ISO26262SafetyRequirementTemplate_ASIL_feature = ASIL
_UI_ISO26262SafetyRequirementTemplate_FTTI_feature = FTTI
_UI_RequirementsModel_requirements_feature = Requirements
_UI_RequirementsModel_derivations_feature = Derivations
_UI_RequirementsModel_satisfactions_feature = Satisfactions
_UI_RequirementsModel_dependencies_feature = Dependencies
_UI_GeneralLibrary_anySituations_feature = Any Situations
_UI_FTA_gates_feature = Gates
_UI_FTA_events_feature = Events
_UI_FTA_trees_feature = Trees
_UI_FTAElement_probability_feature = Probability
_UI_FTAElement_sourceGate_feature = Source Gate
_UI_Event_targetGate_feature = Target Gate
_UI_Event_inhibitGate_feature = Inhibit Gate
_UI_Gate_sourceEvent_feature = Source Event
_UI_Gate_targetEvent_feature = Target Event
_UI_INHIBIT_condition_feature = Condition
_UI_MAJORITY_VOTE_m_feature = M
_UI_FTATree_topEvent_feature = Top Event
_UI_FTATree_gates_feature = Gates
_UI_FTALibrary_ftaElements_feature = Fta Elements
_UI_FTALibrary_gates_feature = Gates
_UI_FMEA_fmeaItems_feature = Fmea Items
_UI_RPNCalculation_RPN_feature = RPN
_UI_RPNCalculation_SEV_feature = SEV
_UI_RPNCalculation_OCC_feature = OCC
_UI_RPNCalculation_DET_feature = DET
_UI_AbstractFMEAItem_RPN_feature = RPN
_UI_AbstractFMEAItem_failureMode_feature = Failure Mode
_UI_AbstractFMEAItem_finalEffect_feature = Final Effect
_UI_AbstractFMEAItem_cause_feature = Cause
_UI_FMEAItem_rpnCalculation_feature = Rpn Calculation
_UI_FMEALibrary_abstractFMEAItems_feature = Abstract FMEA Items
_UI_ISO26262_malfunctioningBehaviors_feature = Malfunctioning Behaviors
_UI_ISO26262_operationalSituations_feature = Operational Situations
_UI_ISO26262_confirmedItems_feature = Confirmed Items
_UI_ISO26262_verifiedItems_feature = Verified Items
_UI_ISO26262_asilAssignments_feature = Asil Assignments
_UI_Verified_result_feature = Result
_UI_Confirmed_result_feature = Result
_UI_ASILAssignment_ASIL_feature = ASIL
_UI_ASILAssignment_ASILOverride_feature = ASIL Override
_UI_AbstractOperationalSituation_exposure_feature = Exposure
_UI_AbstractOperationalSituation_conditions_feature = Conditions
_UI_AccidentScenario_controllability_feature = Controllability
_UI_AccidentScenario_situations_feature = Situations
_UI_AccidentScenario_malfunctioningBehaviors_feature = Malfunctioning Behaviors
_UI_HazardousEvent_ASIL_feature = ASIL
_UI_HazardousEvent_hazards_feature = Hazards
_UI_HazardousEvent_scenarios_feature = Scenarios
_UI_HazardousEvent_vehicleLevelEffects_feature = Vehicle Level Effects
_UI_HazardousEvent_systemLevelEffects_feature = System Level Effects
_UI_ISO26262Library_operationalConditions_feature = Operational Conditions
_UI_ISO26262Library_hazardousEvents_feature = Hazardous Events
_UI_ISO26262Library_accidentScenarios_feature = Accident Scenarios
_UI_STPA_controlStructures_feature = Control Structures
_UI_STPA_losses_feature = Losses
_UI_STPA_hazards_feature = Hazards
_UI_STPA_unsafeControlActions_feature = Unsafe Control Actions
_UI_STPA_controlFlaws_feature = Control Flaws
_UI_Loss_category_feature = Category
_UI_ControlStructure_controllers_feature = Controllers
_UI_ControlStructure_controlledProcesses_feature = Controlled Processes
_UI_ControlStructure_actuators_feature = Actuators
_UI_ControlStructure_sensors_feature = Sensors
_UI_Controller_controlActions_feature = Control Actions
_UI_Controller_feedback_feature = Feedback
_UI_ControlledProcess_receivedActions_feature = Received Actions
_UI_ControlledProcess_providedFeedback_feature = Provided Feedback
_UI_Actuator_executedActions_feature = Executed Actions
_UI_Sensor_providedFeedback_feature = Provided Feedback
_UI_ControlAction_type_feature = Type
_UI_ControlAction_sourceController_feature = Source Controller
_UI_ControlAction_targetProcess_feature = Target Process
_UI_Feedback_type_feature = Type
_UI_Feedback_source_feature = Source
_UI_Feedback_targetController_feature = Target Controller
_UI_UndesiredControlAction_controlAction_feature = Control Action
_UI_UndesiredControlAction_unsafeType_feature = Unsafe Type
_UI_UndesiredControlAction_processModelFlaw_feature = Process Model Flaw
_UI_UndesiredControlAction_harmPotential_feature = Harm Potential
_UI_UndesiredControlAction_causalFactors_feature = Causal Factors
_UI_UndesiredControlAction_scenarios_feature = Scenarios
_UI_STPALibrary_controlStructures_feature = Control Structures
_UI_STPALibrary_controlActions_feature = Control Actions
_UI_STPALibrary_unsafeControlActions_feature = Unsafe Control Actions
_UI_GSN_contextualInformation_feature = Contextual Information
_UI_GSN_gsnNodes_feature = Gsn Nodes
_UI_GSN_supportedBy_feature = Supported By
_UI_GSN_inContextOf_feature = In Context Of
_UI_GSNNode_nodeId_feature = Node Id
_UI_ContextualInformation_contextId_feature = Context Id
_UI_Unknown_feature = Unspecified

_UI_ASIL_noassignment_literal = noassignment
_UI_ASIL_QM_literal = QM
_UI_ASIL_A_literal = A
_UI_ASIL_B_literal = B
_UI_ASIL_C_literal = C
_UI_ASIL_D_literal = D
_UI_ASIL_AB_literal = AB
_UI_ASIL_AC_literal = AC
_UI_ASIL_AD_literal = AD
_UI_ASIL_BC_literal = BC
_UI_ASIL_CD_literal = CD
_UI_ASIL_AA_literal = AA
_UI_ASIL_BB_literal = BB
_UI_ASIL_CC_literal = CC
_UI_ASIL_DD_literal = DD
_UI_ASIL_QMA_literal = QMA
_UI_ASIL_QMB_literal = QMB
_UI_ASIL_QMC_literal = QMC
_UI_ASIL_QMD_literal = QMD
_UI_Controllability_C0_literal = C0
_UI_Controllability_C1_literal = C1
_UI_Controllability_C2_literal = C2
_UI_Controllability_C3_literal = C3
_UI_Exposure_E0_literal = E0
_UI_Exposure_E1_literal = E1
_UI_Exposure_E2_literal = E2
_UI_Exposure_E3_literal = E3
_UI_Exposure_E4_literal = E4
_UI_Severity_S0_literal = S0
_UI_Severity_S1_literal = S1
_UI_Severity_S2_literal = S2
_UI_Severity_S3_literal = S3
