/**
 */
package raaml.fmea.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import raaml.fmea.util.FmeaAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class FmeaItemProviderAdapterFactory extends FmeaAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FmeaItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fmea.FMEA} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FMEAItemProvider fmeaItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fmea.FMEA}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFMEAAdapter() {
		if (fmeaItemProvider == null) {
			fmeaItemProvider = new FMEAItemProvider(this);
		}

		return fmeaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fmea.RPNCalculation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RPNCalculationItemProvider rpnCalculationItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fmea.RPNCalculation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRPNCalculationAdapter() {
		if (rpnCalculationItemProvider == null) {
			rpnCalculationItemProvider = new RPNCalculationItemProvider(this);
		}

		return rpnCalculationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fmea.FMEAItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FMEAItemItemProvider fmeaItemItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fmea.FMEAItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFMEAItemAdapter() {
		if (fmeaItemItemProvider == null) {
			fmeaItemItemProvider = new FMEAItemItemProvider(this);
		}

		return fmeaItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fmea.LossOfFunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LossOfFunctionItemProvider lossOfFunctionItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fmea.LossOfFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLossOfFunctionAdapter() {
		if (lossOfFunctionItemProvider == null) {
			lossOfFunctionItemProvider = new LossOfFunctionItemProvider(this);
		}

		return lossOfFunctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fmea.DegradationOfFunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DegradationOfFunctionItemProvider degradationOfFunctionItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fmea.DegradationOfFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDegradationOfFunctionAdapter() {
		if (degradationOfFunctionItemProvider == null) {
			degradationOfFunctionItemProvider = new DegradationOfFunctionItemProvider(this);
		}

		return degradationOfFunctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fmea.IntermittentFunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntermittentFunctionItemProvider intermittentFunctionItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fmea.IntermittentFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntermittentFunctionAdapter() {
		if (intermittentFunctionItemProvider == null) {
			intermittentFunctionItemProvider = new IntermittentFunctionItemProvider(this);
		}

		return intermittentFunctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fmea.PartialFunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PartialFunctionItemProvider partialFunctionItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fmea.PartialFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPartialFunctionAdapter() {
		if (partialFunctionItemProvider == null) {
			partialFunctionItemProvider = new PartialFunctionItemProvider(this);
		}

		return partialFunctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fmea.ExceedingFunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExceedingFunctionItemProvider exceedingFunctionItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fmea.ExceedingFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExceedingFunctionAdapter() {
		if (exceedingFunctionItemProvider == null) {
			exceedingFunctionItemProvider = new ExceedingFunctionItemProvider(this);
		}

		return exceedingFunctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fmea.UnintendedFunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnintendedFunctionItemProvider unintendedFunctionItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fmea.UnintendedFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnintendedFunctionAdapter() {
		if (unintendedFunctionItemProvider == null) {
			unintendedFunctionItemProvider = new UnintendedFunctionItemProvider(this);
		}

		return unintendedFunctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fmea.DelayedFunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DelayedFunctionItemProvider delayedFunctionItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fmea.DelayedFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDelayedFunctionAdapter() {
		if (delayedFunctionItemProvider == null) {
			delayedFunctionItemProvider = new DelayedFunctionItemProvider(this);
		}

		return delayedFunctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fmea.FMEALibrary} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FMEALibraryItemProvider fmeaLibraryItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fmea.FMEALibrary}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFMEALibraryAdapter() {
		if (fmeaLibraryItemProvider == null) {
			fmeaLibraryItemProvider = new FMEALibraryItemProvider(this);
		}

		return fmeaLibraryItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (fmeaItemProvider != null) fmeaItemProvider.dispose();
		if (rpnCalculationItemProvider != null) rpnCalculationItemProvider.dispose();
		if (fmeaItemItemProvider != null) fmeaItemItemProvider.dispose();
		if (lossOfFunctionItemProvider != null) lossOfFunctionItemProvider.dispose();
		if (degradationOfFunctionItemProvider != null) degradationOfFunctionItemProvider.dispose();
		if (intermittentFunctionItemProvider != null) intermittentFunctionItemProvider.dispose();
		if (partialFunctionItemProvider != null) partialFunctionItemProvider.dispose();
		if (exceedingFunctionItemProvider != null) exceedingFunctionItemProvider.dispose();
		if (unintendedFunctionItemProvider != null) unintendedFunctionItemProvider.dispose();
		if (delayedFunctionItemProvider != null) delayedFunctionItemProvider.dispose();
		if (fmeaLibraryItemProvider != null) fmeaLibraryItemProvider.dispose();
	}

}
