/**
 */
package raaml.fta.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import raaml.fta.util.FtaAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class FtaItemProviderAdapterFactory extends FtaAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FtaItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.FTA} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FTAItemProvider ftaItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.FTA}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFTAAdapter() {
		if (ftaItemProvider == null) {
			ftaItemProvider = new FTAItemProvider(this);
		}

		return ftaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.BasicEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BasicEventItemProvider basicEventItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.BasicEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBasicEventAdapter() {
		if (basicEventItemProvider == null) {
			basicEventItemProvider = new BasicEventItemProvider(this);
		}

		return basicEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.IntermediateEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntermediateEventItemProvider intermediateEventItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.IntermediateEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntermediateEventAdapter() {
		if (intermediateEventItemProvider == null) {
			intermediateEventItemProvider = new IntermediateEventItemProvider(this);
		}

		return intermediateEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.TopEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TopEventItemProvider topEventItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.TopEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTopEventAdapter() {
		if (topEventItemProvider == null) {
			topEventItemProvider = new TopEventItemProvider(this);
		}

		return topEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.ConditionalEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConditionalEventItemProvider conditionalEventItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.ConditionalEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConditionalEventAdapter() {
		if (conditionalEventItemProvider == null) {
			conditionalEventItemProvider = new ConditionalEventItemProvider(this);
		}

		return conditionalEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.DormantEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DormantEventItemProvider dormantEventItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.DormantEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDormantEventAdapter() {
		if (dormantEventItemProvider == null) {
			dormantEventItemProvider = new DormantEventItemProvider(this);
		}

		return dormantEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.UndevelopedEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UndevelopedEventItemProvider undevelopedEventItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.UndevelopedEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUndevelopedEventAdapter() {
		if (undevelopedEventItemProvider == null) {
			undevelopedEventItemProvider = new UndevelopedEventItemProvider(this);
		}

		return undevelopedEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.HouseEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HouseEventItemProvider houseEventItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.HouseEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHouseEventAdapter() {
		if (houseEventItemProvider == null) {
			houseEventItemProvider = new HouseEventItemProvider(this);
		}

		return houseEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.ZeroEvent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ZeroEventItemProvider zeroEventItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.ZeroEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createZeroEventAdapter() {
		if (zeroEventItemProvider == null) {
			zeroEventItemProvider = new ZeroEventItemProvider(this);
		}

		return zeroEventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.AND} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ANDItemProvider andItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.AND}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createANDAdapter() {
		if (andItemProvider == null) {
			andItemProvider = new ANDItemProvider(this);
		}

		return andItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.OR} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ORItemProvider orItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.OR}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createORAdapter() {
		if (orItemProvider == null) {
			orItemProvider = new ORItemProvider(this);
		}

		return orItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.NOT} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NOTItemProvider notItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.NOT}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNOTAdapter() {
		if (notItemProvider == null) {
			notItemProvider = new NOTItemProvider(this);
		}

		return notItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.XOR} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XORItemProvider xorItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.XOR}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXORAdapter() {
		if (xorItemProvider == null) {
			xorItemProvider = new XORItemProvider(this);
		}

		return xorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.SEQ} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SEQItemProvider seqItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.SEQ}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSEQAdapter() {
		if (seqItemProvider == null) {
			seqItemProvider = new SEQItemProvider(this);
		}

		return seqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.INHIBIT} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected INHIBITItemProvider inhibitItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.INHIBIT}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createINHIBITAdapter() {
		if (inhibitItemProvider == null) {
			inhibitItemProvider = new INHIBITItemProvider(this);
		}

		return inhibitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.MAJORITY_VOTE} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MAJORITY_VOTEItemProvider majoritY_VOTEItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.MAJORITY_VOTE}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMAJORITY_VOTEAdapter() {
		if (majoritY_VOTEItemProvider == null) {
			majoritY_VOTEItemProvider = new MAJORITY_VOTEItemProvider(this);
		}

		return majoritY_VOTEItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.FTATree} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FTATreeItemProvider ftaTreeItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.FTATree}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFTATreeAdapter() {
		if (ftaTreeItemProvider == null) {
			ftaTreeItemProvider = new FTATreeItemProvider(this);
		}

		return ftaTreeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.fta.FTALibrary} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FTALibraryItemProvider ftaLibraryItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.fta.FTALibrary}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFTALibraryAdapter() {
		if (ftaLibraryItemProvider == null) {
			ftaLibraryItemProvider = new FTALibraryItemProvider(this);
		}

		return ftaLibraryItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (ftaItemProvider != null) ftaItemProvider.dispose();
		if (basicEventItemProvider != null) basicEventItemProvider.dispose();
		if (intermediateEventItemProvider != null) intermediateEventItemProvider.dispose();
		if (topEventItemProvider != null) topEventItemProvider.dispose();
		if (conditionalEventItemProvider != null) conditionalEventItemProvider.dispose();
		if (dormantEventItemProvider != null) dormantEventItemProvider.dispose();
		if (undevelopedEventItemProvider != null) undevelopedEventItemProvider.dispose();
		if (houseEventItemProvider != null) houseEventItemProvider.dispose();
		if (zeroEventItemProvider != null) zeroEventItemProvider.dispose();
		if (andItemProvider != null) andItemProvider.dispose();
		if (orItemProvider != null) orItemProvider.dispose();
		if (notItemProvider != null) notItemProvider.dispose();
		if (xorItemProvider != null) xorItemProvider.dispose();
		if (seqItemProvider != null) seqItemProvider.dispose();
		if (inhibitItemProvider != null) inhibitItemProvider.dispose();
		if (majoritY_VOTEItemProvider != null) majoritY_VOTEItemProvider.dispose();
		if (ftaTreeItemProvider != null) ftaTreeItemProvider.dispose();
		if (ftaLibraryItemProvider != null) ftaLibraryItemProvider.dispose();
	}

}
