<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="req" nsURI="http://edu.kit.sdq/dsis/metamodels/raaml/req" nsPrefix="req">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Requirements modeling for safety analysis"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="core.ecore#//CoreSafetyElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A safety requirement specification"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Class"/>
      <details key="stereotype" value="Requirement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The requirement text"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Type of requirement (functional, safety, etc.)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Priority level (high, medium, low)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Current status (proposed, approved, implemented, verified)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedElements" upperBound="-1"
        eType="ecore:EClass core.ecore#//CoreSafetyElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Elements related to this requirement"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentRequirement" eType="#//Requirement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Parent requirement in the hierarchy"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childRequirements" upperBound="-1"
        eType="#//Requirement" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Child requirements in the hierarchy"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementComponent" abstract="true"
      eSuperTypes="core.ecore#//CoreSafetyElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for all requirement-related components"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Class"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="haraOwner" eType="#//HazardAndRiskAssessment"
        eOpposite="#//HazardAndRiskAssessment/haraRequirements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abstraction" abstract="true" eSuperTypes="#//RequirementComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for requirement relationships and abstractions"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Abstraction"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeriveRequirement" eSuperTypes="#//Abstraction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Relationship indicating one requirement is derived from another"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Abstraction"/>
      <details key="stereotype" value="DeriveRequirement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Requirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Requirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependenceRequirement" eSuperTypes="#//DeriveRequirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Requirement specifying independence between elements (ISO 26262)"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Abstraction"/>
      <details key="stereotype" value="IndependenceRequirement"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASILDecompose" eSuperTypes="#//DeriveRequirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="ASIL decomposition relationship (ISO 26262) for distributing safety requirements"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Abstraction"/>
      <details key="stereotype" value="ASILDecompose"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Satisfy" eSuperTypes="#//Abstraction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Relationship indicating a requirement satisfies another requirement or element"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Abstraction"/>
      <details key="stereotype" value="Satisfy"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Requirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Requirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserInfoRequirement" eSuperTypes="#//Satisfy">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Requirement specifying information to be provided to users"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Abstraction"/>
      <details key="stereotype" value="UserInfoRequirement"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecoveryRequirement" eSuperTypes="#//Satisfy">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Requirement specifying recovery mechanisms from failures"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Abstraction"/>
      <details key="stereotype" value="RecoveryRequirement"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependabilityRequirement" eSuperTypes="#//Requirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class for dependability and safety requirements"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Class"/>
      <details key="stereotype" value="DependabilityRequirement"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalSafetyRequirement" eSuperTypes="#//DependabilityRequirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Functional safety requirement (FSR) at system level"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Class"/>
      <details key="stereotype" value="FunctionalSafetyRequirement"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareSafetyRequirement" eSuperTypes="#//DependabilityRequirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Software safety requirement derived from technical safety requirements"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Class"/>
      <details key="stereotype" value="SoftwareSafetyRequirement"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HardwareSafetyRequirement" eSuperTypes="#//DependabilityRequirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Hardware safety requirement derived from technical safety requirements"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Class"/>
      <details key="stereotype" value="HardwareSafetyRequirement"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TechnicalSafetyRequirement" eSuperTypes="#//DependabilityRequirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Technical safety requirement (TSR) derived from functional safety requirements"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Class"/>
      <details key="stereotype" value="TechnicalSafetyRequirement"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyGoal" eSuperTypes="#//DependabilityRequirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Top-level safety goal derived from hazard analysis (ISO 26262)"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Class"/>
      <details key="stereotype" value="SafetyGoal"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency" abstract="true" eSuperTypes="#//RequirementComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for requirement dependencies"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Dependency"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Requirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Requirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SafeState" eSuperTypes="#//Dependency">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Definition of a safe state for the system"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Dependency"/>
      <details key="stereotype" value="SafeState"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatingMode" eSuperTypes="#//Dependency">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Specification of an operating mode for the system"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Dependency"/>
      <details key="stereotype" value="OperatingMode"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HazardAndRiskAssessment" eSuperTypes="core.ecore#//CoreSafetyElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container linking hazard analysis to derived requirements"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Class"/>
      <details key="stereotype" value="HazardAndRiskAssessment"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="haraRequirements" upperBound="-1"
        eType="#//RequirementComponent" eOpposite="#//RequirementComponent/haraOwner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ISO26262SafetyRequirementTemplate" eSuperTypes="#//DependabilityRequirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Template for ISO 26262 safety requirements with ASIL and FTTI"/>
    </eAnnotations>
    <eAnnotations source="http://edu.kit.sdq/raaml/metaclass">
      <details key="base" value="Class"/>
      <details key="stereotype" value="ISO26262SafetyRequirementTemplate"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ASIL" eType="ecore:EEnum hara.ecore#//ASIL">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Automotive Safety Integrity Level assigned to this requirement"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FTTI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Fault Tolerant Time Interval in milliseconds"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementsModel" eSuperTypes="core.ecore#//CoreSafetyElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Requirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="derivations" upperBound="-1"
        eType="#//DeriveRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="satisfactions" upperBound="-1"
        eType="#//Satisfy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Dependency" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
