/**
 */
package raaml.hara.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import raaml.hara.util.HaraAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class HaraItemProviderAdapterFactory extends HaraAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public HaraItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.hara.ISO26262} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ISO26262ItemProvider iso26262ItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.hara.ISO26262}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createISO26262Adapter() {
		if (iso26262ItemProvider == null) {
			iso26262ItemProvider = new ISO26262ItemProvider(this);
		}

		return iso26262ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.hara.OperationalSituation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationalSituationItemProvider operationalSituationItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.hara.OperationalSituation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationalSituationAdapter() {
		if (operationalSituationItemProvider == null) {
			operationalSituationItemProvider = new OperationalSituationItemProvider(this);
		}

		return operationalSituationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.hara.MalfunctioningBehaviour} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MalfunctioningBehaviourItemProvider malfunctioningBehaviourItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.hara.MalfunctioningBehaviour}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMalfunctioningBehaviourAdapter() {
		if (malfunctioningBehaviourItemProvider == null) {
			malfunctioningBehaviourItemProvider = new MalfunctioningBehaviourItemProvider(this);
		}

		return malfunctioningBehaviourItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.hara.Verified} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VerifiedItemProvider verifiedItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.hara.Verified}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVerifiedAdapter() {
		if (verifiedItemProvider == null) {
			verifiedItemProvider = new VerifiedItemProvider(this);
		}

		return verifiedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.hara.Confirmed} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfirmedItemProvider confirmedItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.hara.Confirmed}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfirmedAdapter() {
		if (confirmedItemProvider == null) {
			confirmedItemProvider = new ConfirmedItemProvider(this);
		}

		return confirmedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.hara.ASILAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ASILAssignmentItemProvider asilAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.hara.ASILAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createASILAssignmentAdapter() {
		if (asilAssignmentItemProvider == null) {
			asilAssignmentItemProvider = new ASILAssignmentItemProvider(this);
		}

		return asilAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.hara.ISO26262Library} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ISO26262LibraryItemProvider iso26262LibraryItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.hara.ISO26262Library}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createISO26262LibraryAdapter() {
		if (iso26262LibraryItemProvider == null) {
			iso26262LibraryItemProvider = new ISO26262LibraryItemProvider(this);
		}

		return iso26262LibraryItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (iso26262ItemProvider != null) iso26262ItemProvider.dispose();
		if (operationalSituationItemProvider != null) operationalSituationItemProvider.dispose();
		if (malfunctioningBehaviourItemProvider != null) malfunctioningBehaviourItemProvider.dispose();
		if (verifiedItemProvider != null) verifiedItemProvider.dispose();
		if (confirmedItemProvider != null) confirmedItemProvider.dispose();
		if (asilAssignmentItemProvider != null) asilAssignmentItemProvider.dispose();
		if (iso26262LibraryItemProvider != null) iso26262LibraryItemProvider.dispose();
	}

}
