/**
 */
package raaml.req.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import raaml.req.util.ReqAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ReqItemProviderAdapterFactory extends ReqAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ReqItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.Requirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequirementItemProvider requirementItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.Requirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequirementAdapter() {
		if (requirementItemProvider == null) {
			requirementItemProvider = new RequirementItemProvider(this);
		}

		return requirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.DeriveRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeriveRequirementItemProvider deriveRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.DeriveRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeriveRequirementAdapter() {
		if (deriveRequirementItemProvider == null) {
			deriveRequirementItemProvider = new DeriveRequirementItemProvider(this);
		}

		return deriveRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.IndependenceRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IndependenceRequirementItemProvider independenceRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.IndependenceRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIndependenceRequirementAdapter() {
		if (independenceRequirementItemProvider == null) {
			independenceRequirementItemProvider = new IndependenceRequirementItemProvider(this);
		}

		return independenceRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.ASILDecompose} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ASILDecomposeItemProvider asilDecomposeItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.ASILDecompose}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createASILDecomposeAdapter() {
		if (asilDecomposeItemProvider == null) {
			asilDecomposeItemProvider = new ASILDecomposeItemProvider(this);
		}

		return asilDecomposeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.Satisfy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SatisfyItemProvider satisfyItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.Satisfy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSatisfyAdapter() {
		if (satisfyItemProvider == null) {
			satisfyItemProvider = new SatisfyItemProvider(this);
		}

		return satisfyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.UserInfoRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UserInfoRequirementItemProvider userInfoRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.UserInfoRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUserInfoRequirementAdapter() {
		if (userInfoRequirementItemProvider == null) {
			userInfoRequirementItemProvider = new UserInfoRequirementItemProvider(this);
		}

		return userInfoRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.RecoveryRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RecoveryRequirementItemProvider recoveryRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.RecoveryRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRecoveryRequirementAdapter() {
		if (recoveryRequirementItemProvider == null) {
			recoveryRequirementItemProvider = new RecoveryRequirementItemProvider(this);
		}

		return recoveryRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.DependabilityRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependabilityRequirementItemProvider dependabilityRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.DependabilityRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDependabilityRequirementAdapter() {
		if (dependabilityRequirementItemProvider == null) {
			dependabilityRequirementItemProvider = new DependabilityRequirementItemProvider(this);
		}

		return dependabilityRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.FunctionalSafetyRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionalSafetyRequirementItemProvider functionalSafetyRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.FunctionalSafetyRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionalSafetyRequirementAdapter() {
		if (functionalSafetyRequirementItemProvider == null) {
			functionalSafetyRequirementItemProvider = new FunctionalSafetyRequirementItemProvider(this);
		}

		return functionalSafetyRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.SoftwareSafetyRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SoftwareSafetyRequirementItemProvider softwareSafetyRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.SoftwareSafetyRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSoftwareSafetyRequirementAdapter() {
		if (softwareSafetyRequirementItemProvider == null) {
			softwareSafetyRequirementItemProvider = new SoftwareSafetyRequirementItemProvider(this);
		}

		return softwareSafetyRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.HardwareSafetyRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HardwareSafetyRequirementItemProvider hardwareSafetyRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.HardwareSafetyRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHardwareSafetyRequirementAdapter() {
		if (hardwareSafetyRequirementItemProvider == null) {
			hardwareSafetyRequirementItemProvider = new HardwareSafetyRequirementItemProvider(this);
		}

		return hardwareSafetyRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.TechnicalSafetyRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnicalSafetyRequirementItemProvider technicalSafetyRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.TechnicalSafetyRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnicalSafetyRequirementAdapter() {
		if (technicalSafetyRequirementItemProvider == null) {
			technicalSafetyRequirementItemProvider = new TechnicalSafetyRequirementItemProvider(this);
		}

		return technicalSafetyRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.SafetyGoal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SafetyGoalItemProvider safetyGoalItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.SafetyGoal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSafetyGoalAdapter() {
		if (safetyGoalItemProvider == null) {
			safetyGoalItemProvider = new SafetyGoalItemProvider(this);
		}

		return safetyGoalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.SafeState} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SafeStateItemProvider safeStateItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.SafeState}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSafeStateAdapter() {
		if (safeStateItemProvider == null) {
			safeStateItemProvider = new SafeStateItemProvider(this);
		}

		return safeStateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.OperatingMode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperatingModeItemProvider operatingModeItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.OperatingMode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperatingModeAdapter() {
		if (operatingModeItemProvider == null) {
			operatingModeItemProvider = new OperatingModeItemProvider(this);
		}

		return operatingModeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.HazardAndRiskAssessment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HazardAndRiskAssessmentItemProvider hazardAndRiskAssessmentItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.HazardAndRiskAssessment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHazardAndRiskAssessmentAdapter() {
		if (hazardAndRiskAssessmentItemProvider == null) {
			hazardAndRiskAssessmentItemProvider = new HazardAndRiskAssessmentItemProvider(this);
		}

		return hazardAndRiskAssessmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.ISO26262SafetyRequirementTemplate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ISO26262SafetyRequirementTemplateItemProvider iso26262SafetyRequirementTemplateItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.ISO26262SafetyRequirementTemplate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createISO26262SafetyRequirementTemplateAdapter() {
		if (iso26262SafetyRequirementTemplateItemProvider == null) {
			iso26262SafetyRequirementTemplateItemProvider = new ISO26262SafetyRequirementTemplateItemProvider(this);
		}

		return iso26262SafetyRequirementTemplateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link raaml.req.RequirementsModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequirementsModelItemProvider requirementsModelItemProvider;

	/**
	 * This creates an adapter for a {@link raaml.req.RequirementsModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequirementsModelAdapter() {
		if (requirementsModelItemProvider == null) {
			requirementsModelItemProvider = new RequirementsModelItemProvider(this);
		}

		return requirementsModelItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (requirementItemProvider != null) requirementItemProvider.dispose();
		if (deriveRequirementItemProvider != null) deriveRequirementItemProvider.dispose();
		if (independenceRequirementItemProvider != null) independenceRequirementItemProvider.dispose();
		if (asilDecomposeItemProvider != null) asilDecomposeItemProvider.dispose();
		if (satisfyItemProvider != null) satisfyItemProvider.dispose();
		if (userInfoRequirementItemProvider != null) userInfoRequirementItemProvider.dispose();
		if (recoveryRequirementItemProvider != null) recoveryRequirementItemProvider.dispose();
		if (dependabilityRequirementItemProvider != null) dependabilityRequirementItemProvider.dispose();
		if (functionalSafetyRequirementItemProvider != null) functionalSafetyRequirementItemProvider.dispose();
		if (softwareSafetyRequirementItemProvider != null) softwareSafetyRequirementItemProvider.dispose();
		if (hardwareSafetyRequirementItemProvider != null) hardwareSafetyRequirementItemProvider.dispose();
		if (technicalSafetyRequirementItemProvider != null) technicalSafetyRequirementItemProvider.dispose();
		if (safetyGoalItemProvider != null) safetyGoalItemProvider.dispose();
		if (safeStateItemProvider != null) safeStateItemProvider.dispose();
		if (operatingModeItemProvider != null) operatingModeItemProvider.dispose();
		if (hazardAndRiskAssessmentItemProvider != null) hazardAndRiskAssessmentItemProvider.dispose();
		if (iso26262SafetyRequirementTemplateItemProvider != null) iso26262SafetyRequirementTemplateItemProvider.dispose();
		if (requirementsModelItemProvider != null) requirementsModelItemProvider.dispose();
	}

}
